@robo=meu.robo.capture
@url=http://localhost:5000/api/logs


POST {{url}}/{{robo}}/Start
Content-Type: application/json

{
  "Acao": "StartService",
  "Date": "{{$datetime iso8601 -3}}"
}
###

POST {{url}}/{{robo}}/Stop
Content-Type: application/json

{
  "Acao": "StartService",
  "Date": "{{$datetime iso8601 -3}}"
}
###

POST {{url}}/{{robo}}/Error
Content-Type: application/json

{
  "Message": "teste",
  "Date": "{{$datetime iso8601 -3}}"
}

###


POST {{url}}/{{robo}}/Information
Content-Type: application/json

{
  "Message": "teste",
  "Date": "{{$datetime iso8601 -3}}"
}